vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|08 Apr 1999 17:45:00 -0000
vti_extenderversion:SR|5.0.2.2623
vti_lineageid:SR|{DED9C53A-4AEF-45AC-8FCE-168FB7A69004}
vti_cacheddtm:TX|08 Apr 1999 17:45:00 -0000
vti_filesize:IR|226
vti_backlinkinfo:VX|course/os/ex8.html
